### 2) Crear un vector de ceros de tamaño 10

In [1]:
import numpy as np

In [3]:
arr_ceros = np.zeros(10)
arr_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1

In [5]:
arr_ceros[5] = 1
arr_ceros

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

### 4) Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.

In [13]:
arr_50_elem = np.arange(50)
print(arr_50_elem)
arr_50_rev = arr_50_elem[::-1]
print(arr_50_rev)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### 5) Crear una matriz de 3 x 3 con valores del cero al 8

In [15]:
arreglo_num = np.array([0,1,2,3,4,5,6,7,8])
arreglo_num.shape = 3,3
arreglo_num

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 6) Encontrar los indices que no sean cero en un arreglo

In [19]:
arreglo = np.array([1,2,0,0,4,0])
arr_index = np.where(arreglo == 0)
arr_index

(array([2, 3, 5], dtype=int64),)

### 7) Crear una matriz de identidad 3 x 3

In [21]:
mat_ident = np.eye(3)
mat_ident

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 8) Crear una matriz 3 x 3 x 3 con valores randomicos

In [34]:
mat_rand = np.random.randint(0,100,27)
mat_rand.reshape(3,3,3)

array([[[56, 74, 45],
        [50, 20, 64],
        [23, 40, 80]],

       [[87, 85, 15],
        [71,  5, 35],
        [29, 60, 17]],

       [[73, 10, 18],
        [84, 63,  7],
        [60, 22,  3]]])

### 9) Crear una matriz 10 x 10 y encontrar el mayor y el menor

In [41]:
import pandas as pd
mat_rand = np.random.randint(0,50,100)
mat_rand.shape = 10,10
mat_serie = pd.Series(mat_rand.flatten())
print(f'Mayor: ', mat_serie.sort_values(ascending = False).head(1))
print(f'Menor: ', mat_serie.sort_values(ascending = False).tail(1))


Mayor:  72    49
dtype: int32
Menor:  19    0
dtype: int32


### 10) Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)

In [45]:
from scipy import ndimage
from scipy import misc
mapache = misc.face()
mapache

array([[[121, 112, 131],
        [138, 129, 148],
        [153, 144, 165],
        ...,
        [119, 126,  74],
        [131, 136,  82],
        [139, 144,  90]],

       [[ 89,  82, 100],
        [110, 103, 121],
        [130, 122, 143],
        ...,
        [118, 125,  71],
        [134, 141,  87],
        [146, 153,  99]],

       [[ 73,  66,  84],
        [ 94,  87, 105],
        [115, 108, 126],
        ...,
        [117, 126,  71],
        [133, 142,  87],
        [144, 153,  98]],

       ...,

       [[ 87, 106,  76],
        [ 94, 110,  81],
        [107, 124,  92],
        ...,
        [120, 158,  97],
        [119, 157,  96],
        [119, 158,  95]],

       [[ 85, 101,  72],
        [ 95, 111,  82],
        [112, 127,  96],
        ...,
        [121, 157,  96],
        [120, 156,  94],
        [120, 156,  94]],

       [[ 85, 101,  74],
        [ 97, 113,  84],
        [111, 126,  97],
        ...,
        [120, 156,  95],
        [119, 155,  93],
        [118, 154,  92]]

### 11) ¿Como crear una serie de una lista, diccionario o arreglo?

In [66]:
import numpy as np
import pandas as pd
#  pd.DataFrame({'x': pd.Series(['1.0', '2.0', '3.0'], dtype=float), 'y': pd.Series(['1', '2', '3'], dtype=int)})
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

#type (mylist)
df = pd.DataFrame({'lista':pd.Series(mylist), 
                   'array':pd.Series(myarr), 
                   'dicc':pd.Series(mydict)})
df


lista  array  dicc
0      a    0.0   NaN
1      b    1.0   NaN
2      c    2.0   NaN
3      e    3.0   NaN
4      d    4.0   NaN
5      f    5.0   NaN
6      g    6.0   NaN
7      h    7.0   NaN
8      i    8.0   NaN
9      j    9.0   NaN
10     k   10.0   NaN
11     l   11.0   NaN
12     m   12.0   NaN
13     n   13.0   NaN
14     o   14.0   NaN
15     p   15.0   NaN
16     q   16.0   NaN
17     r   17.0   NaN
18     s   18.0   NaN
19     t   19.0   NaN
20     u   20.0   NaN
21     v   21.0   NaN
22     w   22.0   NaN
23     x   23.0   NaN
24     y   24.0   NaN
25     z   25.0   NaN
a    NaN    NaN   0.0
b    NaN    NaN   1.0
c    NaN    NaN   2.0
d    NaN    NaN   4.0
e    NaN    NaN   3.0
f    NaN    NaN   5.0
g    NaN    NaN   6.0
h    NaN    NaN   7.0
i    NaN    NaN   8.0
j    NaN    NaN   9.0
k    NaN    NaN  10.0
l    NaN    NaN  11.0
m    NaN    NaN  12.0
n    NaN    NaN  13.0
o    NaN    NaN  14.0
p    NaN    NaN  15.0
q    NaN    NaN  16.0
r    NaN    NaN  17.0
s    NaN    NaN  18.0
t    NaN    NaN  19.0
u    NaN    NaN  20.0
v    NaN    NaN  21.0
w    NaN    NaN  22.0
x    NaN    NaN  23.0
y    NaN    NaN  24.0
z    NaN    NaN  25.0

### 12) ¿Como convertir el indice de una serie en una columna de un DataFrame?

In [90]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 
# Transformar la serie en dataframe y hacer una columna indice
df1 = pd.DataFrame(ser)
df1.loc[:,'col_index'] = pd.Series(ser,index = df1.index)
print(df1)


    0  col_index
a   0          0
b   1          1
c   2          2
e   3          3
d   4          4
f   5          5
g   6          6
h   7          7
i   8          8
j   9          9
k  10         10
l  11         11
m  12         12
n  13         13
o  14         14
p  15         15
q  16         16
r  17         17
s  18         18
t  19         19
u  20         20
v  21         21
w  22         22
x  23         23
y  24         24
z  25         25


'\n#df1\nserie_index = df1.iloc[:,0]\nserie_index\ntype(serie_index)\ncol_index = serie_index.values # pandas a numpy array\nprint(col_index)\ntype(col_index)\nser\n'

### 13) ¿Como combinar varias series para hacer un DataFrame?

In [94]:
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
## ciudades_concatv = pd.concat([ciudades_uno,ciudades_dos], verify_integrity= True)
## ciudades_concatv
series_concat = ser1.add(ser2)
# series_concat = pd.concat([ser1, ser2], verify_integrity= True)
df1 = pd.DataFrame(series_concat)
print(df1)

TypeError: can only concatenate str (not "int") to str

### 14) ¿Como obtener los items que esten en una serie A y no en una serie B?

In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
#arr_ser1 = ser1.values
#arr_ser2 = ser2.values
for i in ser1
    print( f'$i in serie_valor_ciudad')